config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  get 'sign_up', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to:'messages#create'
  post 'signup', to:'users#create'
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  scope :custom_display, -> { order(:created_at).last(15) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: { minimum: 3, maximum: 15 }
  validates :username, uniqueness: true
  has_secure_password
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def require_user
    return if logged_in?

    flash[:error] = 'You must be logged in to perfom that action'
    redirect_to login_path
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user
  def index
    @message = Message.new
    @messages = Message.includes(:user).custom_display
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    @message = current_user.messages.build(body: message_params)
    return unless @message.save

    ActionCable.server.broadcast 'chatroom_channel',
                                 mod_message: message_render(@message)
  end

  private

  def message_params
    params.require(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: { message: message })
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :loggged_in_redirect, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    # test account login
    if params[:test]
      # random account from 1-5 in database
      session[:user_id] = rand(1..5)
      @user = User.find(session[:user_id])
      flash[:success] = 'You have successfully logged in!'
      redirect_to root_path
      return
    end

    # actual account session login
    @user = User.find_by_username(params[:username])
    if @user&.authenticate(params[:password_digest])
      session[:user_id] = @user.id
      flash[:success] = 'You have successfully logged in!'
      redirect_to root_path
    else
      flash.now[:error] = "There's something wrong with your login information"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have logged out!'
    redirect_to root_path
  end

  private

  def loggged_in_redirect
    return unless logged_in?

    flash[:error] = 'You are already logged in'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(username: params[:username], password: params[:password_digest])
    if @user.save
      flash[:success] = 'You have successfully created an account!'
    else
      flash[:notice] = @user.errors.messages.first
    end
    redirect_to login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatroom/index.html.erb
<%=render 'layouts/centericon'%>
<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id='message-container'>
          <%=render @messages%>
        </div>
      </div>
      <div class="extra content">
        <%=form_with url: "/message" ,class:"ui reply form",remote: true, method:"post" do |f|%>
          <div class="field">
            <div class="ui flui icon input">
              <%= f.text_field :body, placeholder:"Enter a message..."%>
              <%= f.button '<i class="bordered inverted red edit icon"></i>'.html_safe%>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  </div>
  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_centericon.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular red chat icon"></i>
  Say Something
</h4>

app/views/layouts/_messages.html.erb
<%flash.each do | message_type , message |%>
  <div class="ui <%=message_type%> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message %>
    </div>
  </div>
<%end%>

app/views/layouts/_navigation.html.erb
<%=link_to "Chatroom",root_path,class:"item"%>
<a class="item">
  Messages
</a>
<div class="right menu">
  <div class="ui dropdown item">
    Account <i class="dropdown icon"></i>
    <div class="menu">
      <%if logged_in?%>
        <%=link_to 'Logout', logout_path, method: :delete, class:'item'%>
      <%else%>
        <%=link_to "Log in", login_path, class: "item"%>
        <%=link_to "Sign up", sign_up_path, class: "item sign-link"%>
      <%end%>
    </div>
  </div>
  <%if !logged_in?%>
    <div class="item">
      <%=link_to "Sign up", sign_up_path, class: "link-reset sign-link"%>
    </div>
  <%else%>
    <div class="item">
      <p>Logged in as <%=current_user.username%></p>
    </div>
  <%end%>
</div>

app/views/layouts/_signup_form.html.erb
<div class="ui mini modal">
  <i class="close icon"></i>
  <div class="header">
    Sign up form
  </div>
  <div class="content">
    <%= form_with url: "/signup", class:"ui form",method: :post do |form| %>
      <div class="field">
        <%=label_tag 'Username'%>
        <%= form.text_field :username, placeholder:"Username" %>
      </div>
      <div class="field">
        <%=label_tag 'Password'%>
        <%= form.text_field :password_digest, placeholder:"Password" %>
      </div>
      <div class="field">
        <div class="ui checkbox">
          <input type="checkbox" checked="true" tabindex="0" class="hidden">
          <label>I agree to the Terms and Conditions</label>
        </div>
      </div>
      <div class="actions">
        <div class="ui black deny button">
          Cancel
        </div>
        <div class="ui green positive right labeled icon button">
          <a id="submit" class="link-reset2">Submit</a>
          <i class="checkmark icon"></i>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLiveChat</title>
    <%=favicon_link_tag%>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="ui small menu inverted">
      <div class="ui  container">
        <%= render 'layouts/navigation'%>
      </div>
    </div>
    <div class="ui  container">
      <%= render 'layouts/messages'%>
      <%=render 'layouts/signup_form' if !logged_in?%>
      <%= yield %>
    </div>
    <%=console if Rails.env.development?%>
  </body>
</html>

app/views/messages/_message.html.erb
<div class = "event">
  <div class = "content">
    <div class = "summary">
      <em><%=message.user.username%></em>:  <%=message.body%>
    </div>
  </div>
</div>